<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_6405bd213cd95',
        'title' => 'CAPI Events',
        'fields' => array(
            array(
                'key' => 'field_6406db4dc0ffb',
                'label' => 'Enable Browser Events',
                'name' => 'enable_browser_events',
                'type' => 'true_false',
                'instructions' => 'Enable if you wish to fire browser events as well. <b>Note: </b>Pixel code needs to be manually added to the website.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_6405bd7776540',
                'label' => 'Standard Events',
                'name' => 'standard_events',
                'type' => 'repeater',
                'instructions' => 'Transaction-based events such as <strong>Purchase</strong>, <strong>Start Trial</strong> and <strong>Subscribe</strong> are currently not available.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Standard Event',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6405c25abfd47',
                        'label' => 'Event Type',
                        'name' => 'event_type',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'AddPaymentInfo' => 'Add Payment Info',
                            'AddToCart' => 'Add To Cart',
                            'AddToWishlist' => 'Add To Wishlist',
                            'CompleteRegistration' => 'Complete Registration',
                            'Contact' => 'Contact',
                            'CustomizeProduct' => 'Customize Product',
                            'Donate' => 'Donate',
                            'FindLocation' => 'Find Location',
                            'InitiateCheckout' => 'Initiate Checkout',
                            'Lead' => 'Lead',
                            'Schedule' => 'Schedule',
                            'Subscribe' => 'Subscribe',
                            'Search' => 'Search',
                            'SubmitApplication' => 'Submit Application',
                            'ViewContent' => 'View Content',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_6405c3871783c',
                        'label' => 'Fire Event With',
                        'name' => 'fire_event_with',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'css_selector' => 'CSS Selector',
                            'page_load' => 'Specific Page Load',
                            'url_param' => 'URL Parameter',
                            'multi_conditions' => 'Multiple Conditions',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_6405c2a8bfd48',
                        'label' => 'CSS Selector',
                        'name' => 'selector',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6405c3871783c',
                                    'operator' => '==',
                                    'value' => 'css_selector',
                                ),
                            ),
                            array(
                                array(
                                    'field' => 'field_6405c3871783c',
                                    'operator' => '==',
                                    'value' => 'multi_conditions',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6405c44755e36',
                        'label' => 'Page URL',
                        'name' => 'page_url',
                        'type' => 'text',
                        'instructions' => 'specify URl slug',
                        'required' => 1,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6405c3871783c',
                                    'operator' => '==',
                                    'value' => 'page_load',
                                ),
                            ),
                            array(
                                array(
                                    'field' => 'field_6405c3871783c',
                                    'operator' => '==',
                                    'value' => 'multi_conditions',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6405dad6464d8',
                        'label' => 'URL Parameter',
                        'name' => 'url_param',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6405c3871783c',
                                    'operator' => '==',
                                    'value' => 'url_param',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6406cf8bcfa6f',
                        'label' => 'Click Text',
                        'name' => 'click_text',
                        'type' => 'text',
                        'instructions' => 'this will match the clicked link\'s text',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6405c2a8bfd48',
                                    'operator' => '!=empty',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_6405c65b9991d',
                'label' => 'Custom Events',
                'name' => 'custom_events',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Custom Event',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6405c65b9991e',
                        'label' => 'Event Name',
                        'name' => 'event_type',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6405c65b9991f',
                        'label' => 'Fire Event With',
                        'name' => 'fire_event_with',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'css_selector' => 'CSS Selector',
                            'page_load' => 'Specific Page Load',
                            'url_param' => 'URL Parameter',
                            'multi_conditions' => 'Multiple Conditions',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_6405c65b99920',
                        'label' => 'CSS Selector',
                        'name' => 'selector',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6405c65b9991f',
                                    'operator' => '==',
                                    'value' => 'css_selector',
                                ),
                            ),
                            array(
                                array(
                                    'field' => 'field_6405c65b9991f',
                                    'operator' => '==',
                                    'value' => 'multi_conditions',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6405c65b99921',
                        'label' => 'Page URL',
                        'name' => 'page_url',
                        'type' => 'text',
                        'instructions' => 'specify URl slug',
                        'required' => 1,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6405c65b9991f',
                                    'operator' => '==',
                                    'value' => 'page_load',
                                ),
                            ),
                            array(
                                array(
                                    'field' => 'field_6405c65b9991f',
                                    'operator' => '==',
                                    'value' => 'multi_conditions',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6405dbfe23787',
                        'label' => 'URL Parameter',
                        'name' => 'url_param',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6405c65b9991f',
                                    'operator' => '==',
                                    'value' => 'url_param',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6406d7b31a8be',
                        'label' => 'Click Text',
                        'name' => 'click_text',
                        'type' => 'text',
                        'instructions' => 'this will match the clicked link\'s text',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6405c65b99920',
                                    'operator' => '!=empty',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'capi-event-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;

    ## Credentials ##

    if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array(
            'key' => 'group_6406daaf34e48',
            'title' => 'CAPI Credentials',
            'fields' => array(
                array(
                    'key' => 'field_6406db1731a61',
                    'label' => 'Pixel ID',
                    'name' => 'pixel_id',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_6406db2931a62',
                    'label' => 'Access Token',
                    'name' => 'access_token',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_6406db3631a63',
                    'label' => 'Test Event Code',
                    'name' => 'test_event_code',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options-credentials',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));
        
        endif;